// 1. Cấu hình các danh mục
export const CATEGORY_META = [
  { key: 'Action', accent: 'from-cyan-400/30 to-blue-500/10' },
  { key: 'RPG', accent: 'from-fuchsia-400/25 to-purple-500/10' },
  { key: 'Strategy', accent: 'from-emerald-400/25 to-cyan-500/10' },
  { key: 'Simulation', accent: 'from-sky-400/25 to-indigo-500/10' },
  { key: 'Survival & Crafting', accent: 'from-orange-400/25 to-amber-500/10' },
  { key: 'Sports & Racing', accent: 'from-red-400/25 to-pink-500/10' },
  { key: 'MMO/MOBA', accent: 'from-blue-400/25 to-cyan-400/10' },
  { key: 'Roguelike', accent: 'from-violet-400/25 to-fuchsia-500/10' },
  { key: 'Indie', accent: 'from-slate-400/25 to-zinc-500/10' },
];

// 2. Dữ liệu Game Mở Rộng (8-10 game/danh mục để cuộn ngang đẹp mắt)
export const RAW_GAMES = {
  'Action': [
    { title: "Black Myth: Wukong", genre: "Action RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2358720/header.jpg" },
    { title: "Spider-Man Remastered", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/header.jpg" },
    { title: "God of War Ragnarök", genre: "Action Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2322010/header.jpg" },
    { title: "Ghost of Tsushima", genre: "Action Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2215430/header.jpg" },
    { title: "Sekiro: Shadows Die Twice", genre: "Souls-like", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/814380/header.jpg" },
    { title: "Red Dead Redemption 2", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg" },
    { title: "Resident Evil 4", genre: "Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg" },
    { title: "Devil May Cry 5", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/601150/header.jpg" },
    { title: "Left 4 Dead 2", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/550/header.jpg" },
    { title: "Mortal 11 Kombat", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/976310/header.jpg" },
    { title: "Assasin's Creed Odyssey", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/812140/header.jpg" },
    { title: "Assasin's Creed Origins", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/582160/header.jpg" },
    { title: "Assasin's Creed III Remastered", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/911400/header.jpg" },
    { title: "Grand Theft Auto V", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg" },
    { title: "Armored Core VI", genre: "Mecha Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1888160/header.jpg" },
    // --- Đã chuyển từ Other & Other 2 vào ---
    { title: "Suicide Squad: Kill the Justice League", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Assassin’s Creed", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Assassin’s Creed Liberation", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Assassin’s Creed Freedom Cry", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Assassin’s Creed Unity", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Assassin’s Creed Syndicate", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/368500/header.jpg" },
    { title: "Assassin’s Creed® Chronicles: China", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Assassin’s Creed® Chronicles: India", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Assassin’s Creed® Chronicles: Russia", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Assassin’s Creed Rogue", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Batman: Arkham Asylum GOTY Edition", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/35140/header.jpg" },
    { title: "Batman: Arkham City GOTY", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/200260/header.jpg" },
    { title: "Batman™: Arkham Origins", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Batman™: Arkham Knight", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/208650/header.jpg" },
    { title: "Batman™: Arkham Origins Blackgate - Deluxe Edition", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Borderlands 2", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Borderlands 3", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/397540/header.jpg" },
    { title: "Borderlands GOTY", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Borderlands GOTY Enhanced", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Borderlands: The Pre-Sequel", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Bully: Scholarship Edition", genre: "Action", price: "30.000đ", poster: "" },
    { title: "Star Wars Jedi: Fallen Order", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172380/header.jpg" },
    { title: "Ace Combat 7: Skies Unknown", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/502500/header.jpg" },
    { title: "Aliens: Fireteam Elite", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1549970/header.jpg" },
    { title: "Crab Game", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1782210/header.jpg" },
    { title: "Grand Theft Auto: San Andreas", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/12120/header.jpg" },
    { title: "Injustice 2", genre: "Fighting", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/627270/header.jpg" },
    { title: "Just Cause 3", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/225540/header.jpg" },
    { title: "Midnight Ghost Hunt", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/915810/header.jpg" },
    { title: "Naraka: Bladepoint", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1203220/header.jpg" },
    { title: "Warhammer 40,000: Space Marine", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/55150/header.jpg" },
    { title: "Warhammer 40,000: Space Marine 2", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2183900/header.jpg" },
    { title: "Warhammer: Vermintide 2", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/552500/header.jpg" },
    { title: "Warlander", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1283940/header.jpg" }
  ],
  'RPG': [
    { title: "Baldur's Gate 3", genre: "RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg" },
    { title: "Elden Ring", genre: "Action RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg" },
    { title: "The Witcher 3", genre: "RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg" },
    { title: "Cyberpunk 2077", genre: "Action RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg" },
    { title: "Final Fantasy XVI", genre: "JRPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2730330/header.jpg" },
    { title: "Starfield", genre: "Space RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/header.jpg" },
    { title: "Hogwarts Legacy", genre: "Fantasy RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/header.jpg" },
    { title: "Persona 3 Reload", genre: "JRPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2161700/header.jpg" },
    { title: "Dragon's Dogma 2", genre: "RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2054970/header.jpg" },
    // --- Đã chuyển từ Other & Other 2 vào ---
    { title: "Cat Quest", genre: "RPG", price: "30.000đ", poster: "" },
    { title: "Cat Quest II", genre: "RPG", price: "30.000đ", poster: "" },
    { title: "Cat Quest III", genre: "RPG", price: "30.000đ", poster: "" },
    { title: "Elemental Angel II", genre: "RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2422500/header.jpg" }
  ],
  'Strategy': [
    { title: "Total War: WARHAMMER III", genre: "Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1142710/header.jpg" },
    { title: "Age of Empires IV", genre: "RTS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1466860/header.jpg" },
    { title: "Manor Lords", genre: "City Builder", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1363080/header.jpg" },
    { title: "Civilization VI", genre: "Turn-Based", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/289070/header.jpg" },
    { title: "Hearts of Iron IV", genre: "Grand Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/394360/header.jpg" },
    { title: "Frostpunk 2", genre: "Survival Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1601580/header.jpg" },
    { title: "Stellaris", genre: "Space Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/281990/header.jpg" },
    { title: "Company of Heroes 3", genre: "RTS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1677280/header.jpg" },
    // --- Đã chuyển từ Other & Other 2 vào ---
    { title: "Beholder", genre: "Strategy", price: "30.000đ", poster: "" },
    { title: "Beholder 2", genre: "Strategy", price: "30.000đ", poster: "" },
    { title: "Beholder 3", genre: "Strategy", price: "30.000đ", poster: "" },
    { title: "Beholder: Conductor", genre: "Strategy", price: "30.000đ", poster: "" },
    { title: "Company of Heroes", genre: "Strategy", price: "30.000đ", poster: "" },
    { title: "Company of Heroes - Legacy Edition", genre: "Strategy", price: "30.000đ", poster: "" },
    { title: "Company of Heroes 2", genre: "Strategy", price: "30.000đ", poster: "" },
    { title: "Crusader Kings III", genre: "Strategy", price: "30.000đ", poster: "" },
    { title: "Cultist Simulator", genre: "Strategy", price: "30.000đ", poster: "" },
    { title: "Against the Storm", genre: "Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1336490/header.jpg" },
    { title: "Frostpunk", genre: "Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/323190/header.jpg" },
    { title: "Kingdom Rush Alliance", genre: "Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2213760/header.jpg" },
    { title: "Kingdom Rush Vengeance", genre: "Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/752950/header.jpg" },
    { title: "Plants vs. Zombies", genre: "Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3590/header.jpg" },
    { title: "Totally Accurate Battle Simulator", genre: "Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/508440/header.jpg" }
  ],
  'Simulation': [
    { title: "Microsoft Flight Simulator", genre: "Simulation", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1250410/header.jpg" },
    { title: "Euro Truck Simulator 2", genre: "Driving", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/227300/header.jpg" },
    { title: "The Sims 4", genre: "Life Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1222670/header.jpg" },
    { title: "Farming Simulator 22", genre: "Agriculture", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1244460/header.jpg" },
    { title: "Cities: Skylines II", genre: "City Builder", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/949230/header.jpg" },
    { title: "PowerWash Simulator", genre: "Relaxing", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1290000/header.jpg" },
    { title: "House Flipper 2", genre: "Simulation", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1190970/header.jpg" },
    { title: "Contraband Police", genre: "Simulation", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/756800/header.jpg" },
    // --- Đã chuyển từ Other & Other 2 vào ---
    { title: "House Flipper", genre: "Simulation", price: "30.000đ", poster: "" },
    { title: "Barotrauma", genre: "Simulation", price: "30.000đ", poster: "" },
    { title: "Cities: Skylines", genre: "Simulation", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/255710/header.jpg" },
    { title: "Planet Zoo", genre: "Simulation", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/703080/header.jpg" },
    { title: "Love Is All Around", genre: "Simulation", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2322560/header.jpg" }
  ],
  'Survival & Crafting': [
    { title: "Palworld", genre: "Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1623730/header.jpg" },
    { title: "Rust", genre: "Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/252490/header.jpg" },
    { title: "Sons of the Forest", genre: "Horror Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1326470/header.jpg" },
    { title: "Enshrouded", genre: "Crafting", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1203620/header.jpg" },
    { title: "Subnautica", genre: "Open World", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/264710/header.jpg" },
    { title: "Valheim", genre: "Viking Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/892970/header.jpg" },
    { title: "Ark: Survival Ascended", genre: "Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2378510/header.jpg" },
    { title: "The Forest", genre: "Horror Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/242760/header.jpg" },
    // --- Đã chuyển từ Other & Other 2 vào ---
    { title: "7 Days To Die", genre: "Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/251570/header.jpg" },
    { title: "Subnautica: Below Zero", genre: "Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/848450/header.jpg" },
    { title: "ASTRONEER", genre: "Survival", price: "30.000đ", poster: "" },
    { title: "Chernobylite Complete Edition", genre: "Survival", price: "30.000đ", poster: "" },
    { title: "Conan Exiles", genre: "Survival", price: "30.000đ", poster: "" },
    { title: "Core Keeper", genre: "Survival", price: "30.000đ", poster: "" },
    { title: "State of Decay 2", genre: "Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/495420/header.jpg" }
  ],
  'Sports & Racing': [
    { title: "EA SPORTS FC 26", genre: "Sports", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2669320/header.jpg" },
    { title: "EA SPORTS FC 25", genre: "Sports", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2669320/header.jpg" },
    { title: "Forza Horizon 6", genre: "Racing", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg" },
    { title: "Forza Horizon 5", genre: "Racing", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg" },
    { title: "Forza Horizon 4", genre: "Racing", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1293830/header.jpg" },
    { title: "F1 24", genre: "Racing", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2488620/header.jpg" },
    { title: "NBA 2K25", genre: "Sports", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2195250/header.jpg" },
    { title: "Assetto Corsa Competizione", genre: "Simulator", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/805550/header.jpg" },
    { title: "WWE 2K24", genre: "Sports", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2315690/header.jpg" },
    { title: "The Crew Motorfest", genre: "Racing", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2267010/header.jpg" },
    { title: "Need for Speed Unbound", genre: "Racing", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1849250/header.jpg" },
    // --- Đã chuyển từ Other & Other 2 vào ---
    { title: "Dead or Alive Xtreme Venus Vacation", genre: "Sports", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/958260/header.jpg" },
    { title: "Riders Republic", genre: "Sports", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2208920/header.jpg" },
    { title: "Steep", genre: "Sports", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/460920/header.jpg" }
  ],
  'MMO/MOBA': [
    { title: "Lost Ark", genre: "MMORPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1599340/header.jpg" },
    { title: "Dota 2", genre: "MOBA", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/570/header.jpg" },
    { title: "New World", genre: "MMORPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1063730/header.jpg" },
    { title: "Final Fantasy XIV", genre: "MMORPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/39210/header.jpg" },
    { title: "Elder Scrolls Online", genre: "MMORPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/306130/header.jpg" },
    { title: "Black Desert", genre: "MMORPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/582660/header.jpg" },
    { title: "Warframe", genre: "Looter Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/230410/header.jpg" }
  ],
  'Roguelike': [
    { title: "Hades II", genre: "Roguelike", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145350/header.jpg" },
    { title: "Dead Cells", genre: "Action Roguelike", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/588650/header.jpg" },
    { title: "Cult of the Lamb", genre: "Indie Roguelike", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1313140/header.jpg" },
    { title: "Balatro", genre: "Card Roguelike", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2379780/header.jpg" },
    { title: "Vampire Survivors", genre: "Bullet Hell", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1794680/header.jpg" },
    { title: "Risk of Rain 2", genre: "Action Roguelike", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/632360/header.jpg" },
    { title: "Enter the Gungeon", genre: "Roguelike", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/311690/header.jpg" },
    { title: "Slay the Spire", genre: "Card Roguelike", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/646570/header.jpg" },
    // --- Đã chuyển từ Other & Other 2 vào ---
    { title: "The Binding of Isaac", genre: "Roguelike", price: "30.000đ", poster: "" },
    { title: "The Binding of Isaac: Rebirth", genre: "Roguelike", price: "30.000đ", poster: "" },
    { title: "Brotato", genre: "Roguelike", price: "30.000đ", poster: "" }
  ],
  'Indie': [
    { title: "Stardew Valley", genre: "Farming Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg" },
    { title: "Hollow Knight", genre: "Metroidvania", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/header.jpg" },
    { title: "Dave the Diver", genre: "Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1868140/header.jpg" },
    { title: "Lethal Company", genre: "Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1966720/header.jpg" },
    { title: "Untitled Goose Game", genre: "Comedy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1101910/header.jpg" },
    { title: "Outer Wilds", genre: "Exploration", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/753640/header.jpg" },
    { title: "Sea of Stars", genre: "JRPG Indie", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1244090/header.jpg" },
    { title: "Outlast", genre: "JRPG Indie", price: "30.000đ", poster: "https://m.media-amazon.com/images/M/MV5BYTk0Nzg0MWItYWE4Mi00N2Y0LTlkNDAtNzBlNGY1YmZmMzJkXkEyXkFqcGc@._V1_.jpg" },
    { title: "Outlast 2", genre: "JRPG Indie", price: "30.000đ", poster: "https://upload.wikimedia.org/wikipedia/vi/9/94/Outlast2_cover.png" },
    { title: "Cuphead", genre: "Action Indie", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268910/header.jpg" },
    // --- Đã chuyển từ Other & Other 2 vào ---
    { title: "Alien: Isolation", genre: "Horror", price: "30.000đ", poster: "" },
    { title: "Amnesia: A Machine for Pigs", genre: "Horror", price: "30.000đ", poster: "" },
    { title: "Amnesia: Rebirth", genre: "Horror", price: "30.000đ", poster: "" },
    { title: "Amnesia: The Bunker", genre: "Horror", price: "30.000đ", poster: "" },
    { title: "Amnesia: The Dark Descent", genre: "Horror", price: "30.000đ", poster: "" },
    { title: "Among Us", genre: "Party", price: "30.000đ", poster: "" },
    { title: "Beyond: Two Souls", genre: "Adventure", price: "30.000đ", poster: "" },
    { title: "BioShock", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "BioShock Remastered", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "BioShock 2", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "BioShock 2 Remastered", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "BioShock Infinite", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "Black Mesa", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "Buckshot Roulette", genre: "Horror", price: "30.000đ", poster: "" },
    { title: "CHUCHEL", genre: "Puzzle", price: "30.000đ", poster: "" },
    { title: "Counter-Strike", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "Counter-Strike: Condition Zero", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "Counter-Strike: Source", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "Crysis Remastered", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "Crysis 2 Remastered", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "Crysis 3 Remastered", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "Counter-Strike 2", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/header.jpg" },
    { title: "Goose Goose Duck", genre: "Social Deduction", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1568570/header.jpg" },
    { title: "Apex Legends", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/header.jpg" },
    { title: "Backrooms: Apprehension", genre: "Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2172270/header.jpg" },
    { title: "Battlefield 1", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238840/header.jpg" },
    { title: "Battlefield 4", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238860/header.jpg" },
    { title: "Battlefield V", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238810/header.jpg" },
    { title: "Call of Duty", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/header.jpg" },
    { title: "Chained Together", genre: "Platformer", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2555300/header.jpg" },
    { title: "Dark Deception", genre: "Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/332950/header.jpg" },
    { title: "Destiny 2", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1085660/header.jpg" },
    { title: "Destroy All Humans! 2 - Reprobed", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1268700/header.jpg" },
    { title: "Devour", genre: "Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1274570/header.jpg" },
    { title: "DOOM Eternal", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/782330/header.jpg" },
    { title: "The Finals", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2073850/header.jpg" },
    { title: "Hitman 3", genre: "Stealth", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1659040/header.jpg" },
    { title: "Horizon Zero Dawn", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1151640/header.jpg" },
    { title: "Inside the Backrooms", genre: "Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1987080/header.jpg" },
    { title: "It Takes Two", genre: "Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1426210/header.jpg" },
    { title: "Love Choice", genre: "Visual Novel", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/983950/header.jpg" },
    { title: "Overwatch 2", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2357570/header.jpg" },
    { title: "Paper Dolls", genre: "Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/839430/header.jpg" },
    { title: "Party Animals", genre: "Party", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1260320/header.jpg" },
    { title: "Plants vs. Zombies: Garden Warfare", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1911850/header.jpg" },
    { title: "PUBG: BATTLEGROUNDS", genre: "Battle Royale", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/578080/header.jpg" },
    { title: "Ready or Not", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1144200/header.jpg" },
    { title: "Sea of Thieves", genre: "Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172620/header.jpg" },
    { title: "Star Wars Battlefront", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238820/header.jpg" },
    { title: "Star Wars Battlefront II", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238840/header.jpg" },
    { title: "Bandy and the Dark Revival", genre: "Horror", price: "30.000đ", poster: "" },
    { title: "Bendy and the Ink Machine", genre: "Horror", price: "30.000đ", poster: "" },
    { title: "Back 4 Blood", genre: "Shooter", price: "30.000đ", poster: "" },
    { title: "Titanfall 2", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1237970/header.jpg" },
    { title: "Ghost Recon Wildlands", genre: "Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/460930/header.jpg" }
  ]
};