// 1. Cấu hình các danh mục
export const CATEGORY_META = [
  { key: 'Action', accent: 'from-cyan-400/30 to-blue-500/10' },
  { key: 'RPG', accent: 'from-fuchsia-400/25 to-purple-500/10' },
  { key: 'Strategy', accent: 'from-emerald-400/25 to-cyan-500/10' },
  { key: 'Simulation', accent: 'from-sky-400/25 to-indigo-500/10' },
  { key: 'Survival & Crafting', accent: 'from-orange-400/25 to-amber-500/10' },
  { key: 'Sports & Racing', accent: 'from-red-400/25 to-pink-500/10' },
  { key: 'MMO/MOBA', accent: 'from-blue-400/25 to-cyan-400/10' },
  { key: 'Roguelike', accent: 'from-violet-400/25 to-fuchsia-500/10' },
  { key: 'Indie', accent: 'from-slate-400/25 to-zinc-500/10' },
  { key: 'Other', accent: 'from-gray-400/25 to-slate-500/10' }
];

// 2. Dữ liệu Game (Đã loại bỏ trùng lặp tuyệt đối & sửa toàn bộ link ảnh lỗi)
export const RAW_GAMES = {
  'Action': [
    { title: "Black Myth: Wukong", genre: "Action RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2358720/header.jpg" },
    { title: "Marvel's Spider-Man: Miles Morales", genre: "Action Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817190/header.jpg" },
    { title: "Marvel's Spider-Man Remastered", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/header.jpg" },
    { title: "God of War Ragnarok", genre: "Action Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2322010/header.jpg" },
    { title: "Horizon Zero Dawn", genre: "Action RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1151640/header.jpg" },
    { title: "Ghost of Tsushima DIRECTOR'S CUT", genre: "Action Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2215430/header.jpg" },
    { title: "Sekiro: Shadows Die Twice", genre: "Souls-like", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/814380/header.jpg" },
    { title: "Red Dead Redemption 2", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg" },
    { "title": "Death Stranding Director's Cut", "genre": "Action", "price": "30.000đ", "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1850570/header.jpg" },
    { "title": "Metro: Last Light Redux", "genre": "Action", "price": "30.000đ", "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/287390/header.jpg" },
    { "title": "Metro Exodus", "genre": "Action", "price": "30.000đ", "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/412020/header.jpg" },
    { title: "Resident Evil 4 Remake", genre: "Horror Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg" },
    { title: "Devil May Cry 5", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/601150/header.jpg" },
    { title: "Left 4 Dead 2", genre: "Zombie Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/550/header.jpg" },
    { title: "Mortal Kombat 11", genre: "Fighting", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/976310/header.jpg" },
    { title: "Assassin's Creed Odyssey", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/812140/header.jpg" },
    { title: "Assassin's Creed Origins", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/582160/header.jpg" },
    { title: "Assassin's Creed III Remastered", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/911400/header.jpg" },
    { title: "Grand Theft Auto V", genre: "Action Open-World", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg" },
    { title: "Armored Core VI Fires of Rubicon", genre: "Mecha Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1888160/header.jpg" },
    { title: "Suicide Squad: Kill the Justice League", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/315210/header.jpg" },
    { title: "Assassin’s Creed", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/15100/header.jpg" },
    { title: "Assassin’s Creed Liberation HD", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/261760/header.jpg" },
    { title: "Assassin’s Creed Freedom Cry", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/277590/header.jpg" },
    { title: "Assassin’s Creed Unity", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/289650/header.jpg" },
    { title: "Assassin’s Creed Syndicate", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/368500/header.jpg" },
    { title: "Assassin’s Creed® Chronicles: China", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/354380/header.jpg" },
    { title: "Assassin’s Creed® Chronicles: India", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/359610/header.jpg" },
    { title: "Assassin’s Creed® Chronicles: Russia", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/359600/header.jpg" },
    { title: "Assassin’s Creed Rogue", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/311560/header.jpg" },
    { title: "Batman: Arkham Asylum GOTY Edition", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/35140/header.jpg" },
    { title: "Batman: Arkham City GOTY", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/200260/header.jpg" },
    { title: "Batman™: Arkham Origins", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/209000/header.jpg" },
    { title: "Batman™: Arkham Knight", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/208650/header.jpg" },
    { title: "Batman™: Arkham Origins Blackgate - Deluxe Edition", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/267490/header.jpg" },
    { title: "Star Wars Jedi: Fallen Order", genre: "Action Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172380/header.jpg" },
    { title: "Ace Combat 7: Skies Unknown", genre: "Flight Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/502500/header.jpg" },
    { title: "Aliens: Fireteam Elite", genre: "Co-op Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1549970/header.jpg" },
    { title: "Crab Game", genre: "Casual Party", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1782210/header.jpg" },
    { title: "Grand Theft Auto: San Andreas", genre: "Action Classic", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/12120/header.jpg" },
    { title: "Injustice 2", genre: "Fighting", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/627270/header.jpg" },
    { title: "Just Cause 3", genre: "Sandbox Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/225540/header.jpg" },
    { title: "Midnight Ghost Hunt", genre: "Multiplayer Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/915810/header.jpg" },
    { title: "Warhammer 40,000: Space Marine", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/55150/header.jpg" },
    { title: "Warhammer 40,000: Space Marine 2", genre: "Sci-Fi Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2183900/header.jpg" },
    { title: "Warhammer: Vermintide 2", genre: "Co-op Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/552500/header.jpg" },
    { title: "Warlander", genre: "Action Multiplayer", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1283940/header.jpg" },
    { title: "ABO MANDO", genre: "Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/474770/header.jpg" },
    { title: "Abyss Raiders: Uncharted", genre: "Action/Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/331730/header.jpg" },
    { title: "God of War", genre: "Action Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/header.jpg" },
    { title: "Castle Crashers", genre: "Beat 'em up", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/204360/header.jpg" },
    { title: "Half-Life", genre: "Action FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/70/header.jpg" },
    { title: "Horizon Forbidden West™ Complete Edition", genre: "Action RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2420110/header.jpg" },
    { title: "Metro 2033 Redux", genre: "Action Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/286690/header.jpg" },
    { title: "Hitman Absolution", genre: "Stealth Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/203140/header.jpg" },
    { title: "DOOM: The Dark Ages", genre: "Action FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2160910/header.jpg" },
    { title: "DOOM", genre: "FPS Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/379720/header.jpg" },
    { title: "DOOM Eternal", genre: "FPS Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/782330/header.jpg" },
    { title: "Half-Life 2: Deathmatch", genre: "FPS Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/320/header.jpg" },
    { title: "Rainbow Six Siege", genre: "Tactical FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/359550/header.jpg" },
    { title: "Left 4 Dead", genre: "Co-op Zombie Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/500/header.jpg" },
    { title: "darkSector", genre: "Action TPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/29900/header.jpg" },
    { title: "BioShock Remastered", genre: "Action Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/409710/header.jpg" },
    { title: "BioShock 2 Remastered", genre: "Action Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/409720/header.jpg" },
    { title: "BioShock Infinite", genre: "Action FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/8870/header.jpg" },
    { title: "Half-Life 2", genre: "FPS Classic", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/220/header.jpg" },
    { title: "HELLDIVERS™ 2", genre: "Action Co-op", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg" },
    { title: "Wolfenstein II: The New Colossus", genre: "FPS Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/612880/header.jpg" },
    { title: "Control Ultimate Edition", genre: "Action Sci-Fi", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/870780/header.jpg" },
    { title: "Call of Duty®: Modern Warfare® II", genre: "FPS Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/header.jpg" },
    { title: "Halo Infinite", genre: "FPS Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1240440/header.jpg" },
    { title: "TEKKEN 8", genre: "Fighting 3D", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1778820/header.jpg" },
    { title: "Street Fighter™ 6", genre: "Fighting 2D", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1364780/header.jpg" },
    { title: "Mortal Kombat 1", genre: "Fighting", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1971870/header.jpg" },
    { title: "Ratchet & Clank: Rift Apart", genre: "Platformer Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1895880/header.jpg" },
    { title: "Sifu", genre: "Martial Arts Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2138710/header.jpg" },
    { title: "Sleeping Dogs™: Definitive Edition", genre: "Open-World Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/307690/header.jpg" },
    { title: "Nioh 2 – The Complete Edition", genre: "Souls-like Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1325200/header.jpg" },
    { title: "Nioh: Complete Edition", genre: "Souls-like Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/485510/header.jpg" },
    { title: "Devil May Cry HD Collection", genre: "Action Classic", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/631510/header.jpg" },
    { title: "Bayonetta", genre: "Action Hack & Slash", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/460790/header.jpg" },
    { title: "HITMAN World of Assassination", genre: "Stealth Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1659040/header.jpg" },
    { title: "Max Payne 3", genre: "TPS Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/204100/header.jpg" },
    { title: "Wolfenstein: The New Order", genre: "FPS Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/201810/header.jpg" },
    { title: "Marvel's Guardians of the Galaxy", genre: "Sci-Fi Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1088850/header.jpg" },
    { title: "PAYDAY 2", genre: "Co-op Heist FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/218620/header.jpg" },
    { title: "Halo: The Master Chief Collection", genre: "FPS Bundle", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/976730/header.jpg" }
  ],
  'RPG': [
    { title: "Baldur's Gate 3", genre: "CRPG RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg" },
    { title: "Elden Ring", genre: "Souls-like RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg" },
    { title: "The Witcher 3: Wild Hunt", genre: "Open World RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg" },
    { title: "Cyberpunk 2077", genre: "Action RPG Sci-Fi", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg" },
    { title: "Final Fantasy XVI", genre: "JRPG Fantasy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2730330/header.jpg" },
    { title: "Starfield", genre: "Space RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/header.jpg" },
    { title: "Hogwarts Legacy", genre: "Fantasy Magic RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/header.jpg" },
    { title: "Persona 3 Reload", genre: "JRPG Social", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2161700/header.jpg" },
    { title: "Persona 5 Royal", genre: "JRPG Anime", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1687950/header.jpg" },
    { title: "Persona 4 Golden", genre: "JRPG Mystery", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1687940/header.jpg" },
    { title: "Like a Dragon: Infinite Wealth", genre: "Turn-Based RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2070850/header.jpg" },
    { title: "Final Fantasy VII Remake Intergrade", genre: "Action RPG JRPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1462040/header.jpg" },
    { title: "Dragon's Dogma 2", genre: "Fantasy Action RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2054970/header.jpg" },
    { title: "Cat Quest", genre: "Casual RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/593280/header.jpg" },
    { title: "Cat Quest II", genre: "Co-op RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/949280/header.jpg" },
    { title: "Cat Quest III", genre: "Action Casual RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1947110/header.jpg" },
    { title: "Elemental Angel II", genre: "Anime RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2422500/header.jpg" },
    { title: "The First Berserker: Khazan", genre: "Hardcore Action RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2167320/header.jpg" },
    { title: "The Witcher 2: Assassins of Kings", genre: "Story RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/20920/header.jpg" },
    { title: "The Elder Scrolls V: Skyrim Special Edition", genre: "Fantasy RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/489830/header.jpg" },
    { title: "The Witcher: Enhanced Edition", genre: "Classic RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/20900/header.jpg" },
    { title: "Remnant: From the Ashes", genre: "Souls-like Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/617290/header.jpg" },
    { title: "Remnant II", genre: "Shooter Souls-like RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1282100/header.jpg" },
    { title: "Tales of Arise", genre: "JRPG Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/740130/header.jpg" },
    { title: "NieR Replicant™", genre: "Action RPG JRPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1113560/header.jpg" },
    { title: "NieR:Automata™", genre: "Sci-Fi Action RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/524220/header.jpg" },
    { title: "FINAL FANTASY XV", genre: "JRPG Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/637650/header.jpg" },
    { title: "DRAGON BALL Z: KAKAROT", genre: "Anime Fighting RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/851850/header.jpg" },
    { title: "Mass Effect™ Legendary Edition", genre: "Sci-Fi Epic RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1328670/header.jpg" },
    { title: "Yakuza 0", genre: "Beat 'em up RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/813280/header.jpg" },
    { title: "Yakuza Kiwami", genre: "Action Beat 'em up", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/834530/header.jpg" },
    { title: "Yakuza: Like a Dragon", genre: "Turn-Based JRPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1235140/header.jpg" },
    { title: "OCTOPATH TRAVELER II", genre: "Retro JRPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1971650/header.jpg" },
    { title: "Ni no Kuni™ II: Revenant Kingdom", genre: "JRPG Anime", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/589360/header.jpg" },
    { title: "Divinity: Original Sin 2 - Definitive Edition", genre: "Classic Turn-Based RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/435150/header.jpg" },
    { title: "Disco Elysium - The Final Cut", genre: "Detective RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/432530/header.jpg" },
    { title: "Pathfinder: Wrath of the Righteous", genre: "Isometric CRPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1184370/header.jpg" },
    { title: "Grim Dawn", genre: "Action Hack & Slash RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/219990/header.jpg" },
    { title: "Dragon Age: Origins", genre: "Fantasy Dark RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/17450/header.jpg" },
    { title: "Dragon Age™ Inquisition", genre: "Open World RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1222690/header.jpg" },
    { title: "GreedFall", genre: "Action Adventure RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/606880/header.jpg" },
    { title: "Kingdoms of Amalur: Re-Reckoning", genre: "Action RPG Hack", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1041720/header.jpg" },
    { title: "ELEX II", genre: "Sci-Fi Open World RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/900040/header.jpg" },
    { title: "Vampyr", genre: "Dark Action RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/427290/header.jpg" },
    { title: "Fallout 4", genre: "Post-Apocalyptic RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/377160/header.jpg" },
    { title: "Fallout: New Vegas", genre: "FPS Action RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/22380/header.jpg" }
  ],
  'Strategy': [
    { title: "Victoria 3", genre: "Grand Strategy Economy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/529340/header.jpg" },
    { title: "Age of Wonders 4", genre: "Turn-Based Strategy RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1669000/header.jpg" },
    { title: "Wasteland 3", genre: "Tactical Turn-Based RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/719040/header.jpg" },
    { title: "Europa Universalis IV", genre: "Grand Strategy History", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/236850/header.jpg" },
    { title: "Age of Mythology: Retold", genre: "RTS Classic Myth", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1934680/header.jpg" },
    { title: "Total War: THREE KINGDOMS", genre: "Real-Time / Turn-Based", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/364360/header.jpg" },
    { title: "XCOM: Enemy Unknown", genre: "Tactical Turn-Based", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/200510/header.jpg" },
    { title: "Total War: WARHAMMER III", genre: "Fantasy Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1142710/header.jpg" },
    { title: "Manor Lords", genre: "City Builder & RTS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1363080/header.jpg" },
    { title: "Frostpunk 2", genre: "Survival City Builder", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1601580/header.jpg" },
    { title: "Company of Heroes 3", genre: "RTS Tactical WW2", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1677280/header.jpg" },
    { title: "Beholder", genre: "Surveillance Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/475550/header.jpg" },
    { title: "Beholder 2", genre: "Adventure Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/761620/header.jpg" },
    { title: "Beholder 3", genre: "Simulation Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1574090/header.jpg" },
    { title: "Beholder: Conductor", genre: "Management Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2825580/header.jpg" },
    { title: "Company of Heroes", genre: "RTS WW2 Classic", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/228200/header.jpg" },
    { title: "Company of Heroes 2", genre: "RTS WW2 Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/231430/header.jpg" },
    { title: "Cultist Simulator", genre: "Card Strategy Rogue", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/718670/header.jpg" },
    { title: "Against the Storm", genre: "Rogue-lite City Builder", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1336490/header.jpg" },
    { title: "Frostpunk", genre: "Survival Builder", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/323190/header.jpg" },
    { title: "Kingdom Rush Alliance", genre: "Tower Defense Casual", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2213760/header.jpg" },
    { title: "Kingdom Rush Vengeance", genre: "Tower Defense Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/752950/header.jpg" },
    { title: "Plants vs. Zombies", genre: "Tower Defense Classic", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3590/header.jpg" },
    { title: "Totally Accurate Battle Simulator", genre: "Battle Simulation Physics", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/508440/header.jpg" },
    { title: "Mindustry", genre: "Tower Defense Automation", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1127400/header.jpg" },
    { title: "Kingdom Wars 4", genre: "RTS Castle Medieval", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1300730/header.jpg" },
    { title: "TerraScape", genre: "Tile-Building Puzzle", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2298580/header.jpg" },
    { title: "Field of Glory II: Medieval", genre: "Turn-Based Tactical", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1368870/header.jpg" },
    { title: "Frozenheim", genre: "Viking RTS Builder", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1134100/header.jpg" },
    { title: "Reigns", genre: "Card Swipe Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/474750/header.jpg" },
    { title: "XCOM 2", genre: "Tactical Turn-Based Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268500/header.jpg" },
    { title: "Age of Empires II: Definitive Edition", genre: "RTS Classic History", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/813780/header.jpg" }
  ],
  'Simulation': [
    { title: "American Truck Simulator", genre: "Driving Simulator", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/270880/header.jpg" },
    { title: "PC Building Simulator", genre: "Tech Repair Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/621060/header.jpg" },
    { title: "The Sims™ 3", genre: "Life Simulator", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/47890/header.jpg" },
    { title: "Anno 1800", genre: "Industrial City Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/916440/header.jpg" },
    { title: "Jurassic World Evolution 2", genre: "Dino Park Management", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1244460/header.jpg" },
    { title: "Two Point Campus", genre: "University Management", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1649080/header.jpg" },
    { title: "PowerWash Simulator", genre: "Relaxing Cleaner Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1290000/header.jpg" },
    { title: "Surviving Mars", genre: "Sci-Fi Colony Builder", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/464920/header.jpg" },
    { title: "Kerbal Space Program", genre: "Physics Space Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/220200/header.jpg" },
    { title: "Thief Simulator 2", genre: "Action Stealth Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1698560/header.jpg" },
    { title: "Planet Coaster", genre: "Theme Park Builder", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/493340/header.jpg" },
    { title: "Football Manager 2024", genre: "Soccer Management", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2252570/header.jpg" },
    { title: "House Flipper", genre: "Home Renovator Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/613100/header.jpg" },
    { title: "Car Mechanic Simulator 2021", genre: "Car Repair Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1190000/header.jpg" },
    { title: "Microsoft Flight Simulator", genre: "Flight Simulation Physics", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1250410/header.jpg" },
    { title: "Euro Truck Simulator 2", genre: "Truck Driving Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/227300/header.jpg" },
    { title: "The Sims™ 4", genre: "Social Life Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1222670/header.jpg" },
    { title: "Farming Simulator 22", genre: "Agriculture Farming", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1248130/header.jpg" },
    { title: "Cities: Skylines II", genre: "Modern City Builder", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/949230/header.jpg" },
    { title: "House Flipper 2", genre: "Home Design Simulation", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1190970/header.jpg" },
    { title: "Contraband Police", genre: "Border Guard Patrol", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/756800/header.jpg" },
    { title: "Barotrauma", genre: "Submarine Crew Co-op", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/602960/header.jpg" },
    { title: "Cities: Skylines", genre: "Modern City Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/255710/header.jpg" },
    { title: "Planet Zoo", genre: "Wildlife Park Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/703080/header.jpg" },
    { title: "Love Is All Around", genre: "FMV Visual Romance", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2322560/header.jpg" },
    { title: "The Admin", genre: "Action Sci-Fi Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/620700/header.jpg" },
    { title: "The Escapists 2", genre: "Prison Escape Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/641990/header.jpg" },
    { title: "Teardown", genre: "Destruction Sandbox", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1167630/header.jpg" },
    { title: "BeamNG.drive", genre: "Soft-Body Physics Driving", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/284160/header.jpg" },
    { title: "My Singing Monsters", genre: "Monster Breeding Musical", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1419130/header.jpg" },
    { title: "MudRunner", genre: "Off-road Heavy Driving", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/675010/header.jpg" },
    { title: "Liar's Bar", genre: "Casino Social Party", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3006450/header.jpg" },
    { title: "Potion Craft: Alchemist Simulator", genre: "Crafting Merchant Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1210320/header.jpg" },
    { title: "911 Operator", genre: "Emergency Dispatch Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/503560/header.jpg" },
    { title: "Skoof Simulator", genre: "Meme Life Simulator", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2965840/header.jpg" },
    { title: "Russian Fishing 4", genre: "Fishing Simulator MMO", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/766570/header.jpg" },
    { title: "Oxygen Not Included", genre: "Space Colony Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/457140/header.jpg" },
    { title: "Poly Bridge 2", genre: "Bridge Building Physics", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1062160/header.jpg" },
    { title: "Thief Simulator", genre: "Heist Stealth Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/704850/header.jpg" },
    { title: "PlateUp!", genre: "Cooking Co-op Rogue", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1599600/header.jpg" }
  ],
  'Survival & Crafting': [
    { title: "State of Decay 2: Juggernaut Edition", genre: "Zombie Base Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086470/header.jpg" },
    { title: "Green Hell", genre: "Hardcore Jungle Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/815370/header.jpg" },
    { title: "SCUM", genre: "Prisoner Survival Realistic", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/513710/header.jpg" },
    { title: "Icarus", genre: "Session-Based Crafting Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1149460/header.jpg" },
    { title: "Don't Starve Together", genre: "Co-op Wilderness Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/322330/header.jpg" },
    { title: "Project Zomboid", genre: "Isometic Zombie Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/108600/header.jpg" },
    { title: "Valheim", genre: "Viking Crafting Sandbox", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/892970/header.jpg" },
    { title: "7 Days to Die", genre: "Zombie Crafting Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/251570/header.jpg" },
    { title: "The Long Dark", genre: "Winter Wilderness Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/305620/header.jpg" },
    { title: "Conan Exiles", genre: "Barbarian Crafting Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/440900/header.jpg" },
    { title: "Grounded", genre: "Tiny Backyard Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/962130/header.jpg" },
    { title: "Palworld", genre: "Monster Taming Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1623730/header.jpg" },
    { title: "Rust", genre: "Multiplayer Survival PVP", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/252490/header.jpg" },
    { title: "Sons of the Forest", genre: "Cannibal Island Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1326470/header.jpg" },
    { title: "Enshrouded", genre: "Voxel RPG Crafting", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1203620/header.jpg" },
    { title: "Subnautica", genre: "Ocean Survival Crafting", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/264710/header.jpg" },
    { title: "Ark: Survival Ascended", genre: "Dinosaur Crafting Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2378510/header.jpg" },
    { title: "The Forest", genre: "Horror Sandbox Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/242760/header.jpg" },
    { title: "Subnautica: Below Zero", genre: "Deep Frozen Ocean", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/848450/header.jpg" },
    { title: "ASTRONEER", genre: "Interstellar Space Sandbox", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/361420/header.jpg" },
    { title: "Chernobylite Complete Edition", genre: "Radioactive Horor Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1016800/header.jpg" },
    { title: "No Man's Sky", genre: "Procedural Universe Explorer", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/275850/header.jpg" },
    { title: "This War of Mine", genre: "Wartime Civilian Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/282070/header.jpg" },
    { title: "Terraria", genre: "2D Crafting Sandbox Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/105600/header.jpg" },
    { title: "Wild Terra 2", genre: "Isometric MMORPG Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1134700/header.jpg" },
    { title: "Arctico", genre: "Arctic Exploration Sandbox", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/324600/header.jpg" },
    { title: "Starbound", genre: "2D Sci-Fi Crafting Sandbox", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/211820/header.jpg" },
    { title: "Ultimate Zombie Defense", genre: "Top-Down Co-op Defense", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1035510/header.jpg" },
    { title: "Breathedge", genre: "Space Survival Comedy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/738520/header.jpg" },
    { title: "ARK: Survival Evolved", genre: "Classic Dinosaur Survival", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/346110/header.jpg" },
    { title: "Raft", genre: "Ocean Raft Crafting", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/648800/header.jpg" }
  ],
  'Sports & Racing': [
    { "title": "Forza Horizon 6", "genre": "Racing", "price": "30.000đ", "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2443000/header.jpg" },
    { title: "Need for Speed™ Unbound", genre: "Arcade Street Racing", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1846380/header.jpg" },
    { title: "The Crew™ 2", genre: "Open World Driving Motorsports", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/646910/header.jpg" },
    { title: "WWE 2K24", genre: "Sports Wrestling Fighting", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2315690/header.jpg" },
    { title: "PGA TOUR 2K23", genre: "Pro Golf Simulation", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2146110/header.jpg" },
    { title: "WRC 10 FIA World Rally Championship", genre: "Rally Simulation Racing", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1462810/header.jpg" },
    { title: "Riders Republic", genre: "Extreme Sports Multi", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2221920/header.jpg" },
    { title: "EA SPORTS FC 25", genre: "Football Soccer Sports", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2669320/header.jpg" },
    { title: "Forza Horizon 5", genre: "Open-World Racing Simcade", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg" },
    { title: "Forza Horizon 4", genre: "Seasonal Open-World Racing", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1293830/header.jpg" },
    { title: "F1 24", genre: "Formula 1 Pro Racing", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2488620/header.jpg" },
    { title: "NBA 2K25", genre: "Basketball Sports Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2515430/header.jpg" },
    { title: "Assetto Corsa Competizione", genre: "GT3 Pro Racing Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/805550/header.jpg" },
    { title: "The Crew Motorfest", genre: "Hawaiian Open-World Racing", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2267010/header.jpg" },
    { title: "Dead or Alive Xtreme Venus Vacation", genre: "Sports Casual Gacha", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/958260/header.jpg" },
    { title: "Steep", genre: "Winter Alpine Extreme Sports", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/460920/header.jpg" },
    { title: "Assetto Corsa", genre: "Realistic Racing Physics", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/244210/header.jpg" },
    { title: "WRC 7", genre: "Rally Racing Off-Road", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/621090/header.jpg" },
    { title: "Barro", "genre": "Mini-Dirt Racing", "price": "30.000đ", "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/643850/header.jpg" },
    { title: "eFootball", "genre": "Free Football Sports", "price": "30.000đ", "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1665460/header.jpg" },
    { title: "Need for Drive", "genre": "Indie Racing Speed", "price": "30.000đ", "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2633090/header.jpg" },
    { title: "Torque Drift", "genre": "Realistic Pro Drifting", "price": "30.000đ", "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/824030/header.jpg" },
    { title: "Golf With Your Friends", "genre": "Crazy Golf Party", "price": "30.000đ", "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/431240/header.jpg" },
    { title: "Dirt Rally 2.0", genre: "Pro Rally Driving", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/690790/header.jpg" },
    { title: "Need for Speed™ Heat", genre: "Cops vs Racers", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1222680/header.jpg" }
  ],
  'MMO/MOBA': [
    { title: "Lost Ark", genre: "Isometric MMORPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1599340/header.jpg" },
    { title: "Dota 2", genre: "MOBA Strategy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/570/header.jpg" },
    { title: "New World", genre: "Open World MMO RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1063730/header.jpg" },
    { title: "Final Fantasy XIV", genre: "Epic Story MMORPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/39210/header.jpg" },
    { title: "Elder Scrolls Online", genre: "Elder Scrolls RPG MMO", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/306130/header.jpg" },
    { title: "Black Desert", genre: "Action Combat MMORPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/582660/header.jpg" },
    { title: "VRChat", genre: "Virtual Reality Chat MMO", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/438100/header.jpg" },
    { title: "Destiny 2", genre: "Sci-Fi MMO FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1085660/header.jpg" },
    { title: "Apex Legends", genre: "Sci-Fi Hero BR", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/header.jpg" }
  ],
  'Roguelike': [
    { title: "Hades II", genre: "Greek Myth Action Rogue", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145350/header.jpg" },
    { title: "Dead Cells", genre: "Metroidvania Rogue-lite", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/588650/header.jpg" },
    { title: "Cult of the Lamb", genre: "Cult Builder Rogue-lite", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1313140/header.jpg" },
    { title: "Balatro", genre: "Poker Deckbuilder Roguelike", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2379780/header.jpg" },
    { title: "Vampire Survivors", genre: "Gothic Bullet Hell", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1794680/header.jpg" },
    { title: "Risk of Rain 2", genre: "TPS Action Roguelike", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/632360/header.jpg" },
    { title: "Enter the Gungeon", genre: "Action Bullet Hell Rogue", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/311690/header.jpg" },
    { title: "Slay the Spire", genre: "Deckbuilder Card Rogue", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/646570/header.jpg" },
    { title: "The Binding of Isaac", genre: "Classic Roguelike Indie", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/113200/header.jpg" },
    { title: "The Binding of Isaac: Rebirth", genre: "Top-Down Action Rogue", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/250900/header.jpg" },
    { title: "Brotato", genre: "Survival Arena Shooter Rogue", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1942280/header.jpg" },
    { title: "Moonlighter", genre: "Shopkeeper Action RPG Rogue", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/606150/header.jpg" },
    { title: "Blasphemous", genre: "Dark Gothic Metroidvania", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/774361/header.jpg" },
    { title: "Blasphemous 2", genre: "Dark Metroidvania Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2114740/header.jpg" },
    { title: "Hades", genre: "Myth Action Roguelike", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/header.jpg" },
    { title: "Returnal™", genre: "Bullet Hell Sci-Fi Rogue", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1649240/header.jpg" },
    { title: "Darkest Dungeon®", genre: "Turn-Based Gothic Rogue", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/262060/header.jpg" }
  ],
  'Indie': [
    { title: "Hollow Knight: Silksong", genre: "Metroidvania Indie", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1030300/header.jpg" },
    { title: "Hollow Knight", genre: "Metroidvania Gothic", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/header.jpg" },
    { title: "Dave the Diver", genre: "Deep Sea Adventure Sushi", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1868140/header.jpg" },
    { title: "Cuphead", genre: "Retro Animation Boss Run", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268910/header.jpg" },
    { title: "Undertale", genre: "Story Rich Retro RPG", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/391540/header.jpg" },
    { title: "Celeste", genre: "Hardcore Platformer Precision", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/504230/header.jpg" },
    { title: "Ori and the Will of the Wisps", genre: "Beautiful Metroidvania", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1057090/header.jpg" },
    { title: "Ori and the Blind Forest", genre: "Beautiful Metroidvania", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/261570/header.jpg" },
    { title: "Outer Wilds", genre: "Space Loop Mystery", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/753640/header.jpg" },
    { title: "Stray", genre: "Cyberpunk Cat Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1151200/header.jpg" },
    { title: "Inside", genre: "Dark Artistic Platformer", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/304430/header.jpg" },
    { title: "Limbo", genre: "Gothic Mono Platformer", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/48000/header.jpg" },
    { title: "Superliminal", genre: "Perspective Illusion Puzzle", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1049410/header.jpg" },
    { title: "Papers, Please", genre: "Totalitarian Customs Sim", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/239030/header.jpg" },
    { title: "Lethal Company", genre: "Co-op Sci-Fi Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1966720/header.jpg" },
    { title: "Phasmophobia", genre: "Ghost Hunting Co-op", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/739630/header.jpg" },
    { title: "Human: Fall Flat", genre: "Physics Puzzle Party", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/477160/header.jpg" },
    { title: "Outlast", genre: "Found-Footage Asylum Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/238320/header.jpg" },
    { title: "Outlast 2", genre: "Sectarian Wilderness Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/414700/header.jpg" },
    { title: "Alien: Isolation", genre: "Sci-Fi Xenomorph Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/214490/header.jpg" },
    { title: "Amnesia: A Machine for Pigs", genre: "Industrial Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/239200/header.jpg" },
    { title: "Amnesia: Rebirth", genre: "Desert Tomb Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/999220/header.jpg" },
    { title: "Amnesia: The Bunker", genre: "WW1 Bunker Survival Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1944430/header.jpg" },
    { title: "Amnesia: The Dark Descent", genre: "Classic Castle Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/57300/header.jpg" },
    { title: "Among Us", genre: "Social Deduction Space Party", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/945360/header.jpg" },
    { title: "Beyond: Two Souls", genre: "Cinematic Supernatural", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/960990/header.jpg" },
    { title: "Buckshot Roulette", genre: "Tabletop Shotgun Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2835570/header.jpg" },
    { title: "CHUCHEL", genre: "Comedy Cartoon Puzzle", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/711660/header.jpg" },
    { title: "Counter-Strike", genre: "FPS Classic Legacy", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/10/header.jpg" },
    { title: "Counter-Strike: Condition Zero", genre: "FPS Single/Multi", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/80/header.jpg" },
    { title: "Counter-Strike: Source", genre: "FPS Competitive Classic", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/240/header.jpg" },
    { title: "Crysis Remastered", genre: "Sci-Fi Nanosuit FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1280730/header.jpg" },
    { title: "Crysis 2 Remastered", genre: "Sci-Fi Nanosuit FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1283000/header.jpg" },
    { title: "Crysis 3 Remastered", genre: "Sci-Fi Nanosuit FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1283010/header.jpg" },
    { title: "Goose Goose Duck", genre: "Casual Deduction Social", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1568570/header.jpg" },
    { title: "Backrooms: Apprehension", genre: "Liminal Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2172270/header.jpg" },
    { title: "Battlefield 1", genre: "WW1 FPS Epic", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238840/header.jpg" },
    { title: "Battlefield 4", genre: "Modern Warfare FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238860/header.jpg" },
    { title: "Battlefield V", genre: "WW2 FPS Epic", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238810/header.jpg" },
    { title: "Call of Duty: Black Ops", genre: "Cold War FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/42700/header.jpg" },
    { title: "Call of Duty: Modern Warfare 3", genre: "Cinematic War FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/42680/header.jpg" },
    { title: "Call of Duty: Modern Warfare 2", genre: "Cinematic War FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/10180/header.jpg" },
    { title: "Call of Duty: Ghosts", genre: "Tactical War FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/209160/header.jpg" },
    { title: "Call of Duty: WWII", genre: "WW2 Campaign FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/476600/header.jpg" },
    { title: "Chained Together", genre: "Co-op Physics Platformer", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2555300/header.jpg" },
    { title: "Dark Deception", genre: "Fast-Paced Horror Maze", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/332950/header.jpg" },
    { title: "Destroy All Humans! 2 - Reprobed", genre: "Sci-Fi Satire Action", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1268700/header.jpg" },
    { title: "Devour", genre: "Co-op Exorcism Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1274570/header.jpg" },
    { title: "The Finals", genre: "Team Arena Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2073850/header.jpg" },
    { title: "Inside the Backrooms", genre: "Procedural Backrooms Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1987080/header.jpg" },
    { title: "Love Choice", genre: "Cute Visual Novel Romance", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/983950/header.jpg" },
    { title: "Overwatch 2", genre: "Team Hero FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2357570/header.jpg" },
    { title: "Paper Dolls Original", genre: "Asian Haunted Mansion Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/839430/header.jpg" },
    { title: "Party Animals", genre: "Ragdoll Physics Party", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1260320/header.jpg" },
    { title: "Plants vs. Zombies: Garden Warfare", genre: "Wacky Action Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1911850/header.jpg" },
    { title: "Ready or Not", genre: "Hardcore Tactical SWAT FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1144200/header.jpg" },
    { title: "Star Wars Battlefront", genre: "Sci-Fi Battle FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238820/header.jpg" },
    { title: "Star Wars Battlefront II", genre: "Sci-Fi Battle Epic FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238840/header.jpg" },
    { title: "Bendy and the Dark Revival", genre: "Ink-Stylized Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1063660/header.jpg" },
    { title: "Bendy and the Ink Machine", genre: "Ink-Stylized Horror Classic", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/622650/header.jpg" },
    { title: "Back 4 Blood", genre: "Co-op Zombie Shooter", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/924970/header.jpg" },
    { title: "Titanfall 2", genre: "Sci-Fi Mech Action FPS", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1237970/header.jpg" },
    { title: "Ghost Recon Wildlands", genre: "Co-op Military Open World", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/460930/header.jpg" },
    { title: "Above - VR", genre: "Atmospheric VR Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/598230/header.jpg" },
    { title: "Absconding Zatwor", genre: "Casual Escape Indie", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/385000/header.jpg" },
    { title: "Adorables", genre: "Casual Party Animal", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/366760/header.jpg" },
    { title: "The Adventurer - Episode 1: Beginning of the End", genre: "Action Adventure Indie", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/725350/header.jpg" },
    { title: "Adventures of Hooi", genre: "Retro platformer Casual", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/551220/header.jpg" },
    { title: "The Henry Stickmin Collection", genre: "Funny Choice Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1089980/header.jpg" },
    { title: "PEAK", genre: "Artistic Minimalist Platformer", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2892970/header.jpg" },
    { title: "Geometry Dash", genre: "Rhythm-Based Platformer", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/322170/header.jpg" },
    { title: "Your Mother", genre: "Meme Simulation Casual", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2904830/header.jpg" },
    { title: "Split Fiction", genre: "Interactive Narrative Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2765360/header.jpg" },
    { title: "Content Warning", genre: "Spooky Streamer Horror Party", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2881650/header.jpg" },
    { title: "60 Seconds! Reatomized", genre: "Atomic Survival Comedy Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1012630/header.jpg" },
    { title: "Hue", genre: "Color-Shifting Puzzle Indie", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/383270/header.jpg" },
    { title: "The Awesome Adventures of Captain Spirit", genre: "Story Rich Cozy Adventure", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/845070/header.jpg" },
    { title: "Cakey's Twisted Bakery", genre: "Baking Store Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2855660/header.jpg" },
    { title: "Life is Strange 2", genre: "Choice-driven Narrative", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/532210/header.jpg" }
  ],
  'Other': [
    { title: "Little Nightmares", genre: "Puzzle Platformer Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/424840/header.jpg" },
    { title: "Little Nightmares II", genre: "Puzzle Platformer Horror", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/860510/header.jpg" },
    { title: "The Witness", genre: "Open World Line Puzzle", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/210970/header.jpg" },
    { title: "Pummel Party", genre: "Destructive Board Party", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/880940/header.jpg" },
    { title: "Keep Talking and Nobody Explodes", genre: "Co-op Bomb Defusal", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/341800/header.jpg" },
    { title: "Half-Life: Alyx", genre: "VR FPS Masterpiece", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/546560/header.jpg" },
    { title: "Tabletop Simulator", genre: "Physics Board Game Box", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/286160/header.jpg" },
    { title: "Detroit: Become Human", genre: "Cinematic Choice Narrative", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1222140/header.jpg" },
    { title: "Heavy Rain", genre: "Noir Mystery Narrative", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1222130/header.jpg" },
    { title: "Life is Strange Remastered", genre: "Supernatural Teen Story", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1265920/header.jpg" },
    { title: "The Walking Dead: The Telltale Definitive Series", genre: "Emotional Zombie Story", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1449690/header.jpg" },
    { title: "Danganronpa V3: Killing Harmony", genre: "Anime Detective Murder", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/567640/header.jpg" },
    { title: "Phoenix Wright: Ace Attorney Trilogy", genre: "Anime Courtroom Legal", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/787480/header.jpg" },
    { title: "Overcooked! 2", genre: "Chaos Cooking Co-op", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/686810/header.jpg" },
    { title: "It Takes Two", genre: "Co-op Adventure Masterpiece", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1426210/header.jpg" },
    { title: "A Way Out", genre: "Split-Screen Prison Escape", price: "30.000đ", poster: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1222700/header.jpg" }
  ]
};